services:
  postgres:
    image: postgres:13
    restart: always
    environment:
     - DATABASE_HOST=127.0.0.1
     - POSTGRES_DB=nestjs_ecommerce
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=EXZTedK5V5rhaM9GQEJKvRApBT1wA5RCEXZTedK5V5rhaM9GQEJKvRApBT1wA5RC
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  postgres-e2e:
    image: postgres:13
    environment:
      - POSTGRES_DB=db_e2e
      - POSTGRES_USER=e2e
      - POSTGRES_PASSWORD=e2e123
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - postgres
